### ISSUE TITLE
Please add some examples in the README.md

### ISSUE THREAD

**Issue by WillemJiang** [X-lab2017/github-analysis-report-2019#5]
I tried to run the report program by using the data from CDN, it's hard for me to apply the options by just reading about the help information from npm start.
It could be great if we have some examples of command lines to show how to run the report program from scratch.

**Comment by frank-zsy** [comment]
Updated in https://github.com/X-lab2017/github-analysis-report-2019#%E5%88%86%E6%9E%90%E7%A8%8B%E5%BA%8F
